
# start conversation
  GET http://localhost:8081/agentforce/conversation/start 

###

# continue conversation
  POST http://localhost:8081/agentforce/conversation/continue
    ?sessionId=223a0f1b-909a-4cd9-9a6d-c378a6f9c1c5
    &sequenceNumber=1
  content-type: text/plain

  what's the capital of Canada?

###

# end conversation
  GET http://localhost:8081/agentforce/conversation/end
    ?sessionId=223a0f1b-909a-4cd9-9a6d-c378a6f9c1c5