
# start conversation
  GET http://localhost:8081/agentforce/conversation/start 

###

# continue conversation
  POST http://localhost:8081/agentforce/conversation/continue
    ?sessionId=376b5eca-94ac-4acd-81cc-ce0131e241f6
    &sequenceNumber=1
  content-type: text/plain

  how are you doing today?

###

# end conversation
  GET http://localhost:8081/agentforce/conversation/end
    ?sessionId=376b5eca-94ac-4acd-81cc-ce0131e241f6