
# chat - answer prompt
  POST http://localhost:8081/einstein/chat/answerPrompt 
  content-type: text/plain

  how are you doing today?

###

# chat - generate from messages
  POST http://localhost:8081/einstein/chat/generateFromMessages 
  content-type: application/json

  [
    {
        "role": "user",
        "content": "i hate you!"
    },
    {
        "role": "assistant",
        "content": "I apologize that I have upset you. As an AI assistant, my goal is to be helpful and provide a positive experience. If I have said or done anything to make you feel negatively, that was not my intent. I am here to assist you to the best of my abilities. Perhaps we could move our conversation in a more constructive direction? I'm happy to try to address any concerns you may have."
    },
    {
        "role": "user",
        "content": "I didn't mean it. I'm just testing your categories."
    }
  ]

###

# embeddings - adhoc file query
  POST http://localhost:8081/einstein/embeddings/adhocFileQuery
  content-type: text/plain
  
  can I bring my dog?

###

# embeddings - generate from file
  GET http://localhost:8081/einstein/embeddings/generateFromFile

###

# embeddings - generate from text
  POST http://localhost:8081/einstein/embeddings/generateFromText
  content-type: text/plain
  
  Check-in is at 3:00PM. If you arrive prior to check-in, our helpful staff will safely secure your luggage and inform you when your room is ready. Check-out is at 11:00AM, so if your flight departs later, you can easily secure your luggage with us and still enjoy the amenities, like grabbing a bite to eat or laying by the ocean while you wait.